---
- name: using exported facts
  hosts: node3
  tasks:
  - name: install httpd using a fact instead of var
    dnf:
      name: "{{ ansible_facts['ansible_local']['node3_custom_facts']['packages']['web_package'] }}"
      state: present
