---
- name: Example usage of a playbook using secrets
  hosts: all
  vars_files: vars/secrets.yaml
  tasks:
  - name: display the secrets 
    debug:
      msg: "this is the string for {{ username }} this is the string for {{ password }}"
