---
- name: example playbook using vars files list into loop
  hosts: localhost
  vars_files: vars/multivalue.yaml
  tasks:
  - name: output vals to check the correct feeding of vars into loop
    debug:
      msg: "Reading username from vars: {{ item.username }}\nReading homedir from vars: {{ item.homedir }}"
    loop:
      "{{ users }}"
