---
- name: using conditionals as example
  hosts: localhost
  tasks:
  - name: install apache on redhat
    dnf: 
      name: httpd
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  - name: installe apache on debian
    apt:
      name: apache2
      state: present
    when: ansible_facts['os_family'] == "Debian"

