---
- name: testing conditionals and ansible facts example usage
  hosts: localhost
  tasks:
  - name: testing existence of /dev/sda
    debug:
      msg: a disk device /dev/sda exists
    when:
      ansible_facts['devices']['sda'] is defined
  - name: disk /dev/sdc shouldn't exist
    debug:
      msg: dev/sdc does not exist
    when:
      ansible_facts['devices']['sdc'] is not defined

