---
- name: example usage of block with always and rescue
  hosts: node3
  tasks:
  - name: example usage of block
    block:
      - name: remove a file that doesn't not exist
        shell: "rm /home/someuser/somefile"
      - name: ouptut if successful
        debug:
          msg:
            block task was executed
    rescue:
      - name: rescue task example usage
        debug:
          msg: rescue task was executed
    always:
      - name: always task example usage
        debug:
          msg: always task was executed
