---
- name: Create a file with multiline content
  hosts: node2
  tasks:
  - name: Create a file with several lines inside using pipe symbol
    copy:
      content: |
        this is line1
        this is line2
      dest: /home/vagrant/multiline.file
  - name: Create a file concatenating several lines inside using > symbol
    copy:
      content: >
        this is line1
        this is line2
      dest: /home/vagrant/multiline2.file
