---
- name: install packages and set up services
  hosts: all
  vars_files: allvars.yaml
  tasks:
  - name: install packages based on local facts
    dnf:
      state: present
      name:
        - "{{ ansible_local.packages.packages.smb_package }}"
        - "{{ ansible_local.packages.packages.ftp_package }}"
        - "{{ ansible_local.packages.packages.db_package }}"
        - "{{ ansible_local.packages.packages.web_package }}"
        - "{{ ansible_local.packages.packages.firewall_package }}"

- name: setup the lamp services
  hosts: lamp
  vars_files: allvars.yaml
  tasks: 
  - name: start httpd and firewalld services
    service:
      state: started
      enabled: true
      name: "{{ item }}"
    loop: 
      - "{{ ansible_local.services.services.web_service }}"
      -  "{{ ansible_local.services.services.firewall_service }}"
      - "{{ ansible_local.services.services.db_service }}"
  - name: set landing page for httpd
    copy:
      content: "Welcome to the Ansible Web Server"
      dest: "{{ web_root }}/index.html"
  - name: setup firewalld for http and https
    firewalld:
      permanent: true
      immediate: true
      service: "{{ item }}"
      state: enabled
    loop:
      - http
      - https
    notify: 
      - restart firewalld
      - restart httpd
  - name: test httpd page
    uri:
      url: http://node4.rhce-ex294.com
      return_content: true
    register: this
    failed_when: this is faile or 'Ansible' not in this.content 

  handlers:
  - name: restart firewalld
    service:
      name: firewalld 
      state: restarted
  - name: restart httpd
    service:
      name: httpd
      state: restarted

