---
- name: Configure webservices with implicit group-vars
  hosts: webservers
  tasks:
  - name: install software
    dnf:
      name: "{{ web_package }}"
      state: present

  - name: Start and enable httpd
    service:
      name: "{{ web_service }}"
      state: started
      enabled: yes

